version: '3.8'

services:
  api:
    build:
      context: ./src/Trader.Api
      dockerfile: Dockerfile
    container_name: trader-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - OpenRouter__ApiKey=/run/secrets/openrouter_key
      - TraderMade__ApiKey=/run/secrets/tradermade_key
    networks:
      - trader-net
    ports:
      - "80:80"
    secrets:
      - openrouter_key
      - tradermade_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M

  client:
    build:
      context: ./src/Trader.Client
      dockerfile: Dockerfile
    container_name: trader-client
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:80
    networks:
      - trader-net
    ports:
      - "3000:3000"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  trader-net:
    driver: bridge
    name: trader-network

secrets:
  openrouter_key:
    external: true
  tradermade_key:
    external: true
