version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: src/Trader.Api/Dockerfile
    ports:
      - "7000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - TraderMade__ApiKey=${TRADERMADE_API_KEY}
      - OpenRouter__ApiKey=${OPENROUTER_API_KEY}
    restart: unless-stopped
    networks:
      - trader-network

  client:
    build:
      context: .
      dockerfile: src/Trader.Client/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://api
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - trader-network

networks:
  trader-network:
    driver: bridge
